#  __  __ _       _                            _      _ _
# |  \/  (_)     (_)                          | |    (_) |
# | \  / |_ _ __  _  __ _  __ _ _ __ ___   ___| |     _| |__
# | |\/| | | '_ \| |/ _` |/ _` | '_ ` _ \ / _ \ |    | | '_ \
# | |  | | | | | | | (_| | (_| | | | | | |  __/ |____| | |_) |
# |_|  |_|_|_| |_|_|\__, |\__,_|_| |_| |_|\___|______|_|_.__/
#                   __/ |
#                  |___/                 By humandavey
#
# Please read the wiki @ (coming soon)

settings:
  game:
    countdown:
      time: 20
    starting-message:
      - "&e============================"
      - "Welcome to %game%!"
      - ""
      - "%description%"
      - "&e============================"

messages:
  commands:
    no-permission: "&cYou don't have permission to use this command!"
    join:
      usage: "&cUsage: /join <gametype>"
  game:
    joined: "&eYou joined the game!"
    none-available: "&cThere are no games currently available! Please try again later."
    countdown:
      message: "&eThe game will start in %color%%time% &eseconds!"
      title: "%color%%time%"
      subtitle: "&eGet ready to fight!"
    starting-message:
      - "&e============================"
      - "Welcome to %game%!"
      - ""
      - "%description%"
      - "&e============================"