#  __  __ _       _                            _      _ _
# |  \/  (_)     (_)                          | |    (_) |
# | \  / |_ _ __  _  __ _  __ _ _ __ ___   ___| |     _| |__
# | |\/| | | '_ \| |/ _` |/ _` | '_ ` _ \ / _ \ |    | | '_ \
# | |  | | | | | | | (_| | (_| | | | | | |  __/ |____| | |_) |
# |_|  |_|_|_| |_|_|\__, |\__,_|_| |_| |_|\___|______|_|_.__/
#                   __/ |
#                  |___/                 By humandavey
#
# Please read our wiki @ (coming soon)