#  __  __ _       _                            _      _ _
# |  \/  (_)     (_)                          | |    (_) |
# | \  / |_ _ __  _  __ _  __ _ _ __ ___   ___| |     _| |__
# | |\/| | | '_ \| |/ _` |/ _` | '_ ` _ \ / _ \ |    | | '_ \
# | |  | | | | | | | (_| | (_| | | | | | |  __/ |____| | |_) |
# |_|  |_|_|_| |_|_|\__, |\__,_|_| |_| |_|\___|______|_|_.__/
#                   __/ |
#                  |___/                 By humandavey
#
# Please read the wiki @ (coming soon)

settings:

messages:
  commands:
    no-permission: "&cYou don't have permission to use this command!"
    join:
      usage: "&cUsage: /join <gametype>"
  game:
    joined: "&eYou joined the game!"